# Java 抛出

> 原文:[https://www.tutorialandexample.com/java-throws/](https://www.tutorialandexample.com/java-throws/)

**Java throws**:**Java throws**关键字与方法的签名一起使用，表示该方法可能会引发异常。使用 Java *抛出*关键字及其签名的方法不负责处理异常。处理被调用方法引发的异常是调用方方法的责任。因此， **Java throws 关键字将异常处理委托给调用者方法**。

**语法:**

下面提到 Java *throws* 关键字的语法。

```
 accessModifier returnType nameOfMethod() throws Exception1, Exception2 …
 {
   // statements
 } 
```

**Java 抛出关键字示例**

让我们借助一些例子来理解一下 *throws* 关键字的用法。
T3】

### 抛出单一异常

**文件名**:ThrowsExample.java

```
 // import statement
 import java.io.*;
 public class ThrowExample
 {
 // the searchFile() method declares
 // that it may throw the IOException
 public void searchFile() throws IOException
 {
 // the statement may or may not produce IOException
 File f = new File("file.txt");
 FileInputStream str = new FileInputStream(f);
 }
 // main method
 public static void main(String argvs[])
 {
 // Creating an object of the ThrowsExample class
 ThrowsExample thObj = new ThrowsExample();
 try
 {
   // invoking the searchFile() method
   thObj.searchFile();
 }
 catch(IOException io)
 {
   System.out.println(io);
 }
 System.out.println("Code after the try - catch block is executed.");
 }
 } 
```

**输出:**

<figure class="wp-block-image size-large">![Java throws](../Images/d5408faee838ff5568319c4df3dbdb07.png)</figure>

**说明:**在上面的代码中，main()方法负责 *searchFile()* 方法的调用。因此，处理 *IOException* 成为 main()方法的责任，因为 *searchFile()* 方法已经在其签名中使用了 *throws* 关键字。如果从 *searchFile()* 方法的签名中删除了“ *throws IOException* ，那么该方法必须处理引发的*io exception*；否则，编译器会给出一个编译错误作为惩罚。

### 抛出多个异常

throws 关键字还用于引发多个异常。下面的程序说明了同样的情况。

**文件名**:ThrowsExample1.java

```
 // import statement
 import java.io.*;
 public class ThrowsExample1
 {
 // the m() method declares
 // that it may throw the IOException or ClassNotFoundException
 public void m() throws IOException, ClassNotFoundException
 {
 // the statement may or may not produce IOException
 File f = new File("file.txt");
 FileInputStream str = new FileInputStream(f);
 // the statement may or may not produce ClassNotFoundException
 Class.forName("Tutorial&Example");
 }
 // main method
 public static void main(String argvs[])
 {
 // Creating an object of the ThrowsExample1 class
 ThrowsExample1 thObj = new ThrowsExample1();
 // handling multiple exceptions
 try
 {
   // invoking the m() method
   thObj.m();
 }
 catch(IOException io)
 {
   System.out.println(io);
 }
 catch(ClassNotFoundException e)
 {
 System.out.println(e);
 }
 // display statement
 System.out.println("Code after the try - catch block is executed.");
 }
 } 
```

**输出:**

<figure class="wp-block-image size-large">![Java throws](../Images/bc416ff6ec433d59d5725225702dfdef.png)</figure>

### 责任委托

在 Java 中，可以委托处理引发的异常的责任。请遵守以下程序。

**文件名**:ThrowExample2.java

```
 // import statement
 import java.io.*;
 public class ThrowExample2
 {
 // the m() method declares
 // that it may throw the IOException or ClassNotFoundException
 public void m() throws IOException, ClassNotFoundException
 {
 // the statement may or may not produce IOException
 File f = new File("file.txt");
 FileInputStream str = new FileInputStream(f);
 // the statement may or may not produce ClassNotFoundException
 Class.forName("Tutorial&Example");
 }
 // main method
 public static void main(String argvs[]) throws IOException, ClassNotFoundException
 {
 // Creating an object of the ThrowExample2 class
 ThrowExample2 thObj = new ThrowExample2();
 // invoking the m() method
 thObj.m();
 // display statement
 System.out.println("Code after the try - catch block is executed.");
 }
 } 
```

**输出:**

<figure class="wp-block-image size-large">![Java throws](../Images/32d2e8b866d30d892f853bfb78369a64.png)</figure>

**说明:**以上代码是上一个的修改版。在这段代码中，处理引发的异常的 try-catch 块已被移除，main()方法在其签名中使用了 *throws* 关键字。因此，main()方法也委派了处理引发的异常的责任。因为 JVM (Java 虚拟机)调用 main()方法，所以 JVM 处理引发的异常。如果从主方法的签名中删除了 *throws* 关键字，就会出现错误。

### 关于 Java throws 关键字的要点

以下是关于 Java *throws* 关键字需要记住的一些要点。

*   Java throws 关键字必须用于检查异常。对未检查的异常使用 throws 关键字没有任何意义。本教程中使用的示例仅包含已检查的异常。
*   它向编译器提供有关异常的信息。它从不保证程序的正常终止。
*   它向调用方方法提供与异常相关的信息。