# Java 自定义异常

> 原文：<https://www.tutorialandexample.com/java-custom-exception/>

**Java 自定义异常**

Java 语言方便我们创建自己的异常。打算抛出自定义异常的类必须从 Java *异常*或*运行时异常*类中派生。Java *throw* 关键字用于抛出 **Java 自定义异常**。用户可以抛出一个已检查的和未检查的自定义异常。

### 引发自定义检查的异常

要创建自定义检查的异常，必须扩展 Java 异常类。自定义检查的异常在编译时被检测到。下面的程序演示了如何引发自定义检查的异常。

**文件名**:CustomCheckException.java

```
 class NoProperNameException extends Exception
 {
    // constructor of the class NoProperNameException
    NoProperNameException(String m)
    {
       // invoking the constructor of the Exception class
       // to display the desired message
       super(m);
    }
 }
 public class CustomCheckException
 {
 private String stuName;
 private int stuAge;
 // a method for checking the string s contains any letter other than small letter or not
 public boolean containsAlphabet(String s)
 {
   // size of the string s
   int size = s.length();
    // iterating over the characters of the string s
   for (int i = 0; i < size; i++)
   {
      char c = s.charAt(i);
      if (!(c >= 'a' && c <= 'z'))
      {
         // we found a letter which not within range of a to z (all small letters)
         return false;
      }
   }
   return true;
 }
 // declaring that the constructor may throw the NoProperNameException
 public CustomCheckException(int age, String name) throws NoProperNameException
 {
   if(!containsAlphabet(name) && name != null)
   {
      // the string name contains at least one letter, which is not a small letter
      String str = "The name should be proper (Should only contain characters ranging from a to z (all small))";
      NoProperNameException obj = new NoProperNameException(str);
      throw obj;
   }
   this.stuName = name;
   this.stuAge = age;
 }
 // method for displaying the name and age of student
 public void display()
 {
   System.out.println("The Student's name is: "+ this.stuName);
   System.out.println("The Student's age is: "+ this.stuAge);
 }
 // main method
 public static void main(String argvs[])
 {
   String names[] = {"amit", "Sumit"};
   int ages[] = {34, 44};
   // calculating size of the names array
   int size = names.length;
   for(int i = 0 ; i < size; i++)
   {
   // try-catch block for handling any custom exception
   try
   {
     // instantiating the class CustomCheckException
     CustomCheckException obj = new CustomCheckException(ages[i], names[i]);
     // method's name
     obj.display();
   }
   catch(NoProperNameException expn)
   {
    System.out.println("In the catch block " + expn);    
   }
   }
 }
 } 
```

**输出:**

```
 The Student's name is: amit
 The Student's age is: 34
 In the catch block NoProperNameException: The name should be proper (Should only contain characters ranging from a to z (all small)) 
```

**解释:**上面的程序是这样编写的，它只在传递除小写字母以外的任何内容时引发自定义异常。数组名称的第二个字符串包含一个大写字母“S”，因此，第二个字符串“Sumit”会引发自定义异常。

### 引发自定义的未检查异常

未检查的异常是那些在运行时检查的异常。要抛出未检查的异常，必须扩展类 *RuntimeException* 。为了更好的理解，让我们观察下面的程序。

**文件名**:CustomCheckException1.java

```
 class NoCompileTimeException extends RuntimeException
 {
    // constructor of the class NoCompileTimeException
    NoCompileTimeException(String m)
    {
       // invoking the constructor of the Exception class
       // to display the desired message
       super(m);
    }
 }
 public class CustomCheckException1
 {
 // a method for checking whether the number n is greater than 20 or not
 public boolean isGreaterThanTwenty(int n)
 {
     if(n > 20)
     {
         return true;
     }
     return false;
 }
 // declaring that the constructor may throw the NoCompileTimeException
 public CustomCheckException1(int N) throws NoCompileTimeException
 {
   if(isGreaterThanTwenty(N))
   {
      // the string name contains at least one letter, which is not a small letter
      String str = "The numbers should be either less than or greater than 20";
      NoCompileTimeException obj = new NoCompileTimeException(str);
      throw obj;
   }
 }
 // method for displaying the numbers
 public void display(int n)
 {
   System.out.println("The num: "+ n + " is the valid number");
 }
 // main method
 public static void main(String argvs[])
 {
   // input array that contains only numbers
   int numArr[] = {34, 44, 1, 7, 9, 0, 67, 34, 2, 71};
   // calculating size of the numArr array
   int size = numArr.length;
   // iterating over numbr array
   for(int i = 0 ; i < size; i++)
   {
   // try-catch block for handling any custom exception
   try
   {
     // instantiating the class CustomCheckException1
     CustomCheckException1 obj = new CustomCheckException1(numArr[i]);
     // invoking the method display()
     // only gets invoked when there is no exception raised in the try block
     obj.display(numArr[i]);
   }
   catch(NoCompileTimeException expn)
   {
    System.out.println("In the catch block " + expn);    
   }
   }
 }
 } 
```

**输出:**

```
 In the catch block NoCompileTimeException: The numbers should be either less than or greater than 20
 In the catch block NoCompileTimeException: The numbers should be either less than or greater than 20
 The num: 1 is the valid number
 The num: 7 is the valid number
 The num: 9 is the valid number
 The num: 0 is the valid number
 In the catch block NoCompileTimeException: The numbers should be either less than or greater than 20
 In the catch block NoCompileTimeException: The numbers should be either less than or greater than 20
 The num: 2 is the valid number
 In the catch block NoCompileTimeException: The numbers should be either less than or greater than 20 
```

**解释:**上面的程序在遇到大于 20 的数字时抛出异常。