# Java 中用户定义的异常

> 原文:[https://www . tutorialandexample . com/user-defined-exception-in-Java](https://www.tutorialandexample.com/user-defined-exception-in-java)

异常是程序执行时发生的错误(运行时错误)。每当异常发生时，程序会突然停止，并且导致异常的代码行之后的代码从未执行过。

在 Java 中，用户可以自定义异常，这些异常是超级异常类的派生类。自定义异常或用户定义的异常是我们自己创建的。Java 定制异常通常用于根据用户需求定制异常。

示例 sample 1 是一个用户定义的异常，包含 invaliAge，它扩展了 exception 类。

您将通过使用自定义异常向我们提供您的异常描述。我们生成的对象上的 getMessage()函数可用于检索消息，我们已经将该消息提供给继承层次结构的 function Object()，在本例中是异常类。

## 需要使用用户定义的异常

大多数常见类型的计算异常都包含在 Java 异常中。但通常，我们不得不破例。

使用用户定义的异常的几个参数如下:

*   检测当前 Java 异常的子集，并给它们特定的条件。
*   业务逻辑的异常包括业务逻辑或流程异常。理解确切的问题对应用程序用户和程序员都有帮助。

我们必须修改 Java 异常类，以便在 Java.lang 包中创建定制的异常。

在 Java 中创建用户定义异常的示例:

```
public class NameoftheFile extends Exception {  
    public NameoftheFile(String exception) {  
    super(exception);  
    }  
} 
```

**例一:**

 **现在让我们看一个基本的 Java 用户定义异常的例子。示例代码中异常的 function Object()接受一个字符串作为输入。super()函数用于将该字符串赋予超类异常的函数对象()。同样，在调用异常类的 function Object()时，也不需要调用 super()方法或使用参数。

**UserDefinedException1.java**

```
// class UserDefinedException1 denotes the creation of user-defined exception
class AgeException extends Exception  
{  
    public AgeException(String st)  
    {  
        // A constructor of the Parent class Exception is called  
        super(st);  
    }  
}  

// class using the user-defined AgeException  
public class UserDefinedException1  
{  

    //this block contains the method for checking the age condition 
    static void check(int age) throws  AgeException 
    {
       if(age < 18)
       {  

        //  an object is used for throwing the Exception
        throw new AgeException("Invalid age");    
       }  
       else
      {   
        System.out.println("Person can eligible");   
      }   
     }    

    // main section of the program 
    public static void main(String args[])  
    {  
        try  
        {  
            // calling the check method   
            check(15);  
        }  
        catch (AgeException e)  
        {  
            System.out.println("Found an exception");  

            //the message is printing from the AgeException class  
            System.out.println("The Exception occurred is: " + e);  
        }  

        System.out.println("Other lines of the code....");    
    }  
} 
```

**输出:**

<figure class="wp-block-image">![User Defined Exception in Java](../Images/af93fd427767e053c7f492bf40c58b76.png)</figure>

在上面的例子中，当人物(页面)被认为是 15 岁时，则显示出现了异常的无效年龄。

**例二:**

 ****UserDefinedException2.java**

```
// class UserDefinedException2 denotes the user-defined exception 
class MyException extends Exception  
{  

}  

// MyException class using the user-defined Exception 
public class UserDefinedException2
{  
    // main section  
    public static void main(String args[])  
    {  
        try  
        {  
            // an object is used for throwing the Exception
            throw new MyException();  
        }  
        catch (MyException ex)  
        {  
            System.out.println("found an exception");  
            System.out.println(ex.getMessage());  
        }  

        System.out.println("other lines of code");    
    }  
} 
```

**输出:**

![User Defined Exception in Java](../Images/2cc6cb0a83dffbf240414ef0b47c96b4.png)****